version: "3"
services:
  web:
    build: .
    restart: always
    env_file:
      - ./.env
      - ./.env.secret
    command: gunicorn --bind 0.0.0.0:8080 aristotle.wsgi
    volumes:
      - .:/www
    ports:
      - "8080:8080"
    depends_on:
      - nginx
  nginx:
    image: "nginx"
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    ports:
      - "80:80"
  db:
    image: "postgres"
    restart: always
    env_file:
      - ./.env.secret
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data